name: NodeJS CI

on: [push]

jobs:
    ci:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: ['20.x']

        steps:
            - uses: actions/checkout@v4

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'

            - name: Install Dependencies
              run: npm ci

            - name: Build Check
              run: npm run check

            - name: Lint
              run: npm run lint

            - name: Tests
              run: npm test
